### ISSUE TITLE
Semicolons after export statements are optional.

### ISSUE THREAD

**Issue by diachedelic** [jslint-org/jslint#282]
JSLint produces no warnings for the following program, yet the program is missing a trailing semicolon.

```
export default Object.freeze({})
```

This appears to be due to [this if statement](https://github.com/douglascrockford/JSLint/blob/bca8b225a376352899d634442802b241fee8b97b/jslint.js#L3402), which looks intentional.

**Comment by kaizhu256** [comment]
thx. fixed in pr #301 with regression-test

**Comment by diachedelic** [comment]
Thanks!
