### ISSUE TITLE
migrate jslint.com to gh-pages

### ISSUE THREAD

**Issue by kaizhu256** [jslint-org/jslint#288]
@douglascrockford 

figured out how to transfer jslint.com to github.
1. create root-file /CNAME in gh-pages with content "www.jslint.com"  -- DONE
2. in dns-provider add following `A` and `CNAME` records:

| name | type | ttl | data |
|--|--|--|--|
| @ | A | 1h | 185.199.108.153 |
| @ | A | 1h | 185.199.109.153 |
| @ | A | 1h | 185.199.110.153 |
| @ | A | 1h | 185.199.111.153 |
| www | CNAME | 1h | jslint-org.github.io |

like  screenshot below

------------------------
![image](https://user-images.githubusercontent.com/280571/118896297-8428b980-b8cd-11eb-8de7-80ab1383f6cd.png)

------------------------

wait 1 hour (or set ttl to 5m for faster refresh) and `jslint.com/www.jslint.com` should redirect to gh-pages.
verified process works with my custom-domain.

![image](https://user-images.githubusercontent.com/280571/118896968-0796da80-b8cf-11eb-928c-bbae59593872.png)

**Comment by kaizhu256** [comment]
thx!

**Comment by kaizhu256** [comment]
forgot about assets from `jslint.com/function.html` and `jslint.com/help.html`  ^^;;;

if they still exist, can you upload below missing assets to `gh-page` branch?
```
https://jslint.com/image/jslintpill.gif
https://jslint.com/image/github.gif
https://jslint.com/image/jsonpill.gif
https://jslint.com/image/1and1pill.gif
```

![image](https://user-images.githubusercontent.com/280571/118932094-40ee3b00-b90d-11eb-8793-793c111b1173.png)

**Comment by douglascrockford** [comment]
They should be deleted.
