### ISSUE TITLE
installation instructions are missing

### ISSUE THREAD

**Issue by matkoniecz** [jslint-org/jslint#291]
Neither https://www.jslint.com/index.html nor https://github.com/jslint-org/jslint#jslint-the-javascript-code-quality-tool nor https://www.jslint.com/help.html seems to explain what is the standard installation method

**Comment by kaizhu256** [comment]
yes its a problem.  the current hack to run cli is using the shell-function [shJslintCli](https://github.com/jslint-org/jslint/blob/v2021.5.21/ci.sh#L383)

```shell
#!/bin/sh
. ci.sh
shJslintCli foo.js # jslint single file
shJslintCli .      # jslint all .js files in current directory
```

i eventually want to merge `shJsLintCli`'s nodejs code into `jslint.js` so installation simply involves downloading jslint.js from cdn and running it directly:

```shell
#!/bin/sh
curl -L https://jslint.com/jslint.js > jslint.mjs
node jslint.mjs foo.js # jslint single file
node jslint.mjs .      # jslint all .js files in current directory
```

to run it programmatically, again simply download `jslint.js` from cdn

```sh
#!/bin/sh
curl -L https://jslint.com/jslint.js > jslint.mjs

node --input-type=module -e '
import jslint from "./jslint.mjs"
let code = ...
let result = jslint(code); # jslint programmatically
result.warnings.forEach(function (warning) {
    console.error(warning);
});
'
```

@douglascrockford what do you think?
