### ISSUE TITLE
The future of JSLint

### ISSUE THREAD

**Issue by SOULPWRD** [jslint-org/jslint#308]
Hi!

Is this the official repository for JSLint? Because I wanted to lint some parts of my code and all of a sudden the `async` keyword is staring at me.

I'm just curious what has happened to such a strict tool as JSLint is so it started to support some of relatively new JS features/concepts. I'm just asking because I've been a fan of the Crockford's sceptical and minimalistic approach to the language and now I've become a bit confused. I recall he's been sceptical about for instance `async await`, native generator functions, symbols etc. Has he changed his mind?

Is JSLint turning into some kind of Prettier style linter? What's the future of JSLint?

Thanks for the answer.

**Comment by douglascrockford** [comment]
I still think async et al were really bad ideas. 

I am impressed with Kai Zhu, so I have put JSLint in his care.

**Comment by kaizhu256** [comment]
planned roadmap is in the [Todo section of CHANGELOG.md](https://github.com/jslint-org/jslint/blob/beta/CHANGELOG.md#todo)

1. async/await was motivated to improve ergonomics with i/o heavy libraries like google-puppeteer.

2. there's also plans to replace most of the recursive-code in jslint.js with while/for loops for easier readability (and allowing newcomers to contribute to the core-logic as well).

3. i'm toying with the idea of integrating https://github.com/CSSLint/csslint as well making `jslint.js` a "tool-less", all-in-one file that could lint everything in a web-project.

so aside from async/await and moving away from recursion,
there are no plans to support native generator functions, symbols, and generally any feature that "is sometimes dangerous, and there is a better option"

**Comment by SOULPWRD** [comment]
Thanks to both of you for the answer.

Last small question: Is there an open group/forum for a broader audience as it used to be on Google+?

**Comment by douglascrockford** [comment]
No. Perhaps we can do something like that on Github?
