### ISSUE TITLE
Bug report: Highlighting code and indenting not working

### ISSUE THREAD

**Issue by UnrealApex** [jslint-org/jslint#339]
**Describe the bug**
1. When highlighting multiple lines and pressing `tab` deletes selection instead of indenting it. `shift+tab` also doesn't work but doesn't delete anything highlighted when

2. Jslint edition: `v2021.7.1-beta`

**Expected behavior**

When highlighting lines and pressing tab, the lines would be indented.

**Comment by kaizhu256** [comment]
should b fixed. thx for reporting.
