### ISSUE TITLE
Feature request: Providing a link to a JavaScript file to lint

### ISSUE THREAD

**Issue by UnrealApex** [jslint-org/jslint#348]
It would be nice to be able to provide a link to a file e.g `https://www.example.com/script.js` for linting as an alternative to copying the contents of the file and pasting them into JSLint.

**Comment by kaizhu256** [comment]
closing this feature-request as infeasible-at-moment since it would require a backend/external server to process cors-requests.  jslint.com currently is a static website.

**Comment by UnrealApex** [comment]
@kaizhu256 we could use an [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) to retrieve content of webpages without the need of a server(works with static sites): 

```javascript
function reqListener () {
  // set the value of the editor textarea to the response text
  console.log(this.responseText);
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "http://www.example.org/example.txt");
oReq.send();
```

**Comment by kaizhu256** [comment]
it doesn't work.  copy-paste the following code in your browser's console, and you'll see the http-request is refused.  the only way to get around it is if jslint.com has a backend-server to serve as proxy.

```js
await fetch("https://www.example.org/example.txt")
```

![image](https://user-images.githubusercontent.com/280571/148708027-c7d59e0d-173f-45cc-9d95-da99580b78a7.png)

**Comment by UnrealApex** [comment]
I'm a little busy at the moment, when I get time, I'll verify it.
