### ISSUE TITLE
Switch statement crashes jslint

### ISSUE THREAD

**Issue by davideder** [jslint-org/jslint#358]
**Describe the bug**
1. A clear and concise description of what the bug is.

jslint test.js
 1. [JSLint was unable to finish] Cannot read property 'disrupt' of undefined // line 1, column 1
    
TypeError: [JSLint was unable to finish] Cannot read property 'disrupt' of undefined
    at parse_statements (file:///opt/jslint/jslint.mjs:4231:35)
    at jslint_phase3_parse (file:///opt/jslint/jslint.mjs:6347:24)
    at jslint (file:///opt/jslint/jslint.mjs:862:9)
    at jslint_from_file (file:///opt/jslint/jslint.mjs:1075:24)
    at jslint_cli (file:///opt/jslint/jslint.mjs:1275:5)
 2. Expected 'switch' to be in a function. // line 1, column 1
    switch(a)
 3. Expected statements before 'default'. // line 4, column 3
    default:

2. Jslint edition:

v2021.9.20

3. Code snippet (if applicable):

switch(a)
{
  case 1:
  default:
}

**Expected behavior**

Expect it to not get a TypeError

**Comment by kaizhu256** [comment]
thx for reporting.  should be fixed in cl fce38bcc

![image](https://user-images.githubusercontent.com/280571/135515556-befd91f2-1062-49ff-9a54-fd37e757794f.png)
