### ISSUE TITLE
Feature request: Using cookies to save selected options

### ISSUE THREAD

**Issue by UnrealApex** [jslint-org/jslint#369]
**Is your feature request related to a problem? Please describe.**
It would be nice if JSLint saved the options you selected for future linting.

**Describe the solution you'd like**
Saving which settings are checked/unchecked using cookies.

**Describe alternatives you've considered**
Just setting the options every time I use JSLint(_very_ often and love it)

**Comment by kaizhu256** [comment]
thx for reporting.  closing this issue as fixed by pr #391
