### ISSUE TITLE
Gray (and no red) could shown in Warning section, if no warnings

### ISSUE THREAD

**Issue by valju** [jslint-org/jslint#383]
**Is your feature request related to a problem? Please describe.**
Now red color on the report output, even if no warnings or errors

**Describe the solution you'd like**
When no warnings, the colors in that section could be green or gray

**Comment by 17dian** [comment]
这是来自foxmail邮箱的自动回复邮件。      您好,您的邮件已经收到，我查阅后，尽快给您回复。

**Comment by rajSaheel** [comment]
Hey Repo owner,
I want to work on this issue, with your permission.
Hoping to hear soon!

**Comment by kaizhu256** [comment]
@rajSaheel, sure you're welcome contribute a pr : )

**Comment by kaizhu256** [comment]
closing this as won't fix.

- this is subjective, but having the warning-section colored gray or green, feels "weird" to me

- i purposely want users to be aware of the *big red* warning-section, even when their code is free of jslint-warnings.
