### ISSUE TITLE
JavaScript Classes ?

### ISSUE THREAD

**Issue by ThibaudLopez** [jslint-org/jslint#425]
Does jslint support JavaScript Classes, or plan to in the future?

This example from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes),

```js
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}
```

throws `Undeclared 'class'`, `Undeclared 'constructor'`, and other errors in [jslint.com](https://jslint.com) `v2023.1.29`.

Thanks

**Comment by kaizhu256** [comment]
no, there's no plan to support js classes
