### ISSUE TITLE
Feature request: vscode-jslint – lint on save (or lint automatically)

### ISSUE THREAD

**Issue by fourier-space** [jslint-org/jslint#429]
I hope this is the right place to file this, as it's about the vscode extension rather than jslint core. But [it's page](https://marketplace.visualstudio.com/items?itemName=jslint.vscode-jslint) links to this github.

**Is your feature request related to a problem? Please describe.**
To use this extension, you have to actively run the command to lint the file (by the context menu or key binding).
There is no feature to automatically invoke the linter, such as on save.
This issue is a request for such feature!

**Describe the solution you'd like**
If appropriately enabled, when a javascript file is saved, the linter is run at this point.

**Describe alternatives you've considered**
The ["Andrew Hyndman" jslint extension](https://marketplace.visualstudio.com/items?itemName=ajhyndman.jslint), which is a good interface but lags behind in jslint version, lints on each character. This is good too.

**Comment by kaizhu256** [comment]
- yes this is the right place to file
- +1 for manual, lint-on-save hotkey `ctrl+shift+j s` (or `cmd+shift+j s` for mac)
- -1 for automatic, lint-on-save
  - most javascript-in-the-wild follow conventions incompatible with jslint
  - more time will be lost trying to disable automatic lint-on-save (common-case), than gained from the feature

**Comment by cprivitere** [comment]
> * yes this is the right place to file
> * +1 for manual, lint-on-save hotkey `ctrl+shift+j s` (or `cmd+shift+j s` for mac)
> * -1 for automatic, lint-on-save
>   
>   * most javascript-in-the-wild follow conventions incompatible with jslint
>   * more time will be lost trying to disable automatic lint-on-save (common-case), than gained from the feature

The problem with this thought process is that once you've finished linting, you still have to manually lint on save. Having to do it manually each time is annoying and it's not consistent with other linters. I understand the default should be off, but vscode is quite configurable and having an option to turn automatic lint-on-save would be wonderful.
