### ISSUE TITLE
JSLint error on Private class features

### ISSUE THREAD

**Issue by erosman** [jslint-org/jslint#435]
**Describe the bug**
JSLint error on [Private class features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)

```js
class ClassWithPrivate {
  #privateField;
  #privateFieldWithInitializer = 42;

  #privateMethod() {
    // …
  }
}

class ClassWithStaticPrivate {
  static #privateField;
  static #privateFieldWithInitializer = 42;

  static #privateMethod() {
    // …
  }
}
```
> JSLint - [JSLint was unable to finish] Unexpected character '#'.

**Jslint edition:**
vscode-jslint v2023.4.29

**Expected behavior**
No error

**Comment by kaizhu256** [comment]
jslint doesn't support es-classes or private fields.  there a no plans to implement this support.
