### ISSUE TITLE
Bug report: Don't support async await 

### ISSUE THREAD

**Issue by mernsolution** [jslint-org/jslint#438]
**Describe the bug**
export async function RegistrationApi(userName,userMail, 
userPassword, userPhoto) {
try {
Store.dispatch(showLoader());
const URL = `${Base_url}/register`;
const postBody = {
 userMail,
 userName,
 userPassword,
 userPhoto
};
const res = await axios.post(URL, postBody);
if (res.status === 200) {
return true;
} else {
toast.error("Failed to register");
return false;
}
} catch (error) {
Store.dispatch(HideLoader());
 console.log(error);
 return false;
}
}
Problem JsLint  can not read async and await my code is okay but jsLint say warning

**Comment by kaizhu256** [comment]
thx for reporting.  jslint now has proper grammar for recognizing `export async function ...`
