### ISSUE TITLE
Feature request: vim integration - allow custom directory in config

### ISSUE THREAD

**Issue by bunglegrind** [jslint-org/jslint#455]
**Is your feature request related to a problem? Please describe.**
As stated in the title, the vim integration assumes jslint files in .vim directory. But in Windows, the default directory is vimfiles

**Describe the solution you'd like**
Passing the directory as a parameter in .vimrc

**Describe alternatives you've considered**
Change the path according to the platform vim is running

See: https://superuser.com/questions/119991/how-do-i-get-vim-home-directory

**Comment by kaizhu256** [comment]
- thx for reporting, should be fixed now
- you can save vim-plugin + jslint.mjs into any directory and it should run fine from there.
    - see updated README @ https://github.com/jslint-org/jslint?tab=readme-ov-file#quickstart-jslint-in-vim

**Comment by bunglegrind** [comment]
Mmm...I don't think it's working...the command is correctly registered but it does not output anything

**Comment by bunglegrind** [comment]
`expand("<sfile>:p:h")`  gives you the path of the directory you're in, not the path of .vim or vimfiles, because it is inside a function. You may:
1. let the user set the path in a variable in .vimrc
1. Take the first path of  the runtime variable
1. mimic a closure using a dictionary function (I'm not fluent in vimscript, so you should check its feasibility http://ujihisa.blogspot.com/2010/11/something-like-closure-for-vim-script.html )

**Comment by kaizhu256** [comment]
can you download the alpha-version @ https://raw.githubusercontent.com/jslint-org/jslint/alpha/jslint_wrapper_vim.vim and see if it works?

**Comment by bunglegrind** [comment]
> can you download the alpha-version @ https://raw.githubusercontent.com/jslint-org/jslint/alpha/jslint_wrapper_vim.vim and see if it works?

I've just replaced jslint_wrapper_vim.vim with the alpha version and now it woks! Thanks!
